tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/core"

cask "1password"
cask "aerial"
cask "alfred"
cask "elgato-control-center"
cask "google-chrome"
cask "logitech-camera-settings"
cask "logitech-options"
cask "sizeup"
cask "skype"
cask "vlc"
cask "zoomus"
